# Generated by Django 2.2.7 on 2019-11-22 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20191122_1519'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticlePost',
        ),
    ]
